const GUI_DEFAULT_VALUES = {
	DEFAULT_FONT_SIZE_IN_PX: 13,
	DEFAULT_PADDING_TOP_IN_PX: 5,
	DEFAULT_PADDING_BOTTOM_IN_PX: 5,
	DEFAULT_PADDING_LEFT_IN_PX: 15,
	DEFAULT_PADDING_RIGHT_IN_PX: 15,
	DEFAULT_CORNER_RADIUS_SMALL: 3,
	DEFAULT_CORNER_RADIUS_MEDIUM: 5,
	DEFAULT_CORNER_RADIUS_BIG: 10,
};

export default GUI_DEFAULT_VALUES;
