import { IBasePlayerCharacterControllerConstructorParams } from '@mmorpg/interfaces/controllers/player/IBasePlayerCharacterController';

type IPlayerCharacterInventoryControllerConstructorParams = IBasePlayerCharacterControllerConstructorParams;

export { IPlayerCharacterInventoryControllerConstructorParams };
